### ISSUE TITLE
Getting "failed to parse off timer data from response"

### ISSUE THREAD

**Issue by avnerernst** [TomerFi/home-assistant-custom-components#6]
I'm able to change the switch state correctly but the log is full with "failed to parse off timer data from response". probably getting it during timer interval. any reason for that?

**Comment by TomerFi** [comment]
It seems like something is wrong in broadcast message going out from the device.
What is your firmware version?
What is the auto-off setting on your device?

Can you please add the following configuration to you `configuration.yaml` file:
```yaml
logger:
  default: error
  logs:
    custom_components.switcher_aio: debug
```
